#List of ranks

[[ranks]]
	tier = 1
	numAffixes = 1
	defaultColor = 16776960
	chance = 0.15
	growthFactor = 2

[[ranks]]
	tier = 2
	numAffixes = 2
	defaultColor = 16744448
	chance = 0.30
	growthFactor = 4

[[ranks]]
	tier = 3
	numAffixes = 3
	defaultColor = 16711680
	chance = 0.20
	growthFactor = 8

[[ranks]]
	tier = 4
	numAffixes = 4
	defaultColor = 11141375
	chance = 0.10
	growthFactor = 14
	effects = ["minecraft:resistance;0"]
