
[general]
	#Enable debug for game testing
	enableDebug = false
	#The range from an active beacon where no champions will spawn (0 to disable)
	#Range: 0 ~ 1000
	beaconProtectionRange = 64
	#Set to true to enable champions from mob spawners
	championSpawners = true
	#The minimum tier of champions that will have death messages sent out upon defeat (0 to disable)
	#Range: > 0
	deathMessageTier = 3
	#A list of dimension names that are blacklisted/whitelisted for champions
	dimensionList = []
	#Set whether the dimension list is a blacklist or whitelist
	#Allowed Values: BLACKLIST, WHITELIST
	dimensionPermission = "BLACKLIST"
	#A list of entities that are blacklisted/whitelisted for champions
	entitiesList = ["minecraft:ender_dragon", "minecraft:wither", "minecraft:warden", "minecraft:elder_guardian", "twilightforest:naga", "twilightforest:lich", "twilightforest:hydra", "twilightforest:ur_ghast", "twilightforest:knight_phantom", "twilightforest:snow_queen", "twilightforest:minoshroom", "twilightforest:alpha_yeti", "blue_skies:summoner", "blue_skies:alchemist", "blue_skies:starlit_crusher", "blue_skies:arachnarch", "aether:slider", "aether:valkyrie_queen", "aether:sun_spirit", "deep_aether:eots_controller", "undergarden:forgotten_guardian", "undergarden:forgotten", "deeperdarker:stalker", "deeperdarker:shattered", "deeperdarker:shriek_worm", "deeperdarker:sculk_centipede", "cataclysm:netherite_monstrosity", "cataclysm:ignis", "cataclysm:ender_guardian", "cataclysm:ancient_remnant", "cataclysm:the_leviathan", "cataclysm:the_harbinger", "cataclysm:maledictus", "cataclysm:ender_golem", "cataclysm:ignited_revenant", "botania:doppleganger", "meetyourfight:swampjaw", "meetyourfight:bellringer", "meetyourfight:dame_fortuna", "meetyourfight:rosalyne", "mutantmonsters:mutant_zombie", "mutantmonsters:mutant_skeleton", "mutantmonsters:mutant_creeper", "mutantmonsters:mutant_enderman", "stalwart_dungeons:shelterer", "stalwart_dungeons:nether_keeper", "stalwart_dungeons:awful_ghast", "stalwart_dungeons:incomplete_wither", "keebsz:tower_guardian", "irons_spellbooks:dead_king", "irons_spellbooks:fire_boss", "irons_spellbooks:citadel_keeper", "theabyss:soul_guard", "theabyss:ice_knight", "ub:sorcerer", "ub:storm", "majestic_menaces:teikoku_senshi"]
	#Set whether the entities list is a blacklist or whitelist
	#Allowed Values: BLACKLIST, WHITELIST
	entitiesPermission = "BLACKLIST"
	#Set to true to show HUD display for champions, including health, affixes, and tier
	showHud = true
	#Set entity id (for example, ['minecraft:end_dragon', 'minecraft:creeper']) to hidden HUD display for champions, including health, affixes, and tier
	bossBarBlackList = []
	#Set to true to have champions generate a colored particle effect indicating their rank
	showParticles = true
	#Set to true to show champion tier and affixes in The One Probe overlay
	enableTOPIntegration = true
	#Set to true to enable champions entity allow list configuration by datapack
	allowChampionsList = true
	#The permission of champions entity allow list datapack.
	#Allowed Values: BLACKLIST, WHITELIST
	allowChampionsPermission = "WHITELIST"

