#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue May 05 10:50:52 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
