#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Apr 22 16:04:59 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
