#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Apr 20 14:12:07 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
