modLoader="lowcodefml"
loaderVersion="[40,)"

[[mods]]
modId="icraft"
version="1.0.0"
displayName="IridescentCraft Data"
description="Iridescent Codex (Patchouli book) + advancement data for IridescentCraft"

[[dependencies.icraft]]
modId="patchouli"
mandatory=false
versionRange="[1.20.1-85,)"
ordering="AFTER"
side="BOTH"
