// Hide duplicate food/crop items from JEI to canonicalize on Pam HC2.
//
// Generated by audit pass 2026-05-12. See wiki/design/changelog.md for
// the decision matrix (which mod wins on which overlap). Items here
// are still craftable from their host mod's NATIVE recipes (if any) but
// hidden from search so players see ONE canonical version per concept.
// Removing them entirely would break worlds with existing stacks; this
// is the soft cleanup.
//
// Hide categories:
//   1. Thermal Cultivation crops/cakes that duplicate Pam HC2
//   2. Vanilla Cookbook items that duplicate Pam HC2 / Farmer's Delight
//   3. Pam HC2 FoodExt internal duplicates of FoodCore / Crops
//   4. FD-addon raw crops/seeds that duplicate Pam HC2 (Cultural / Delightful)
//   5. Blue Skies items duplicating Pam HC2

JEIEvents.hideItems(event => {
  const hides = [
    // -- Thermal Cultivation (canonical: Pam HC2) --
    'thermal:amaranth', 'thermal:amaranth_block',
    'thermal:barley', 'thermal:barley_block',
    'thermal:carrot_cake',
    'thermal:chocolate_cake',
    'thermal:cooked_corn', 'thermal:cooked_eggplant',
    'thermal:corn', 'thermal:corn_block',
    'thermal:dough',
    'thermal:eggplant', 'thermal:eggplant_block',
    'thermal:flax', 'thermal:flax_block',
    'thermal:flour',
    'thermal:onion', 'thermal:onion_block',
    'thermal:peanut', 'thermal:peanut_block',
    'thermal:peanut_butter',
    'thermal:radish', 'thermal:radish_block',
    'thermal:rice', 'thermal:rice_block',
    'thermal:spinach', 'thermal:spinach_block',
    'thermal:spring_salad',
    'thermal:strawberry', 'thermal:strawberry_block',
    'thermal:stuffed_pepper',
    'thermal:tomato', 'thermal:tomato_block',

    // -- Blue Skies (canonical: Pam HC2) --
    'blue_skies:maple_sapling',

    // -- Vanilla Cookbook (canonical: Pam HC2 / Farmer's Delight) --
    'vanillacookbook:apple_juice',
    'vanillacookbook:apple_pie',
    'vanillacookbook:bacon_pancake',
    'vanillacookbook:baked_apple',
    'vanillacookbook:brownie',
    'vanillacookbook:carrot_cake',
    'vanillacookbook:cheese',
    'vanillacookbook:chicken_soup',
    'vanillacookbook:chocolate_cake',
    'vanillacookbook:chocolate_ice_cream',
    'vanillacookbook:chocolate_milk',
    'vanillacookbook:chorus_juice',
    'vanillacookbook:cooked_egg',
    'vanillacookbook:fish_and_chips',
    'vanillacookbook:fish_stew',
    'vanillacookbook:french_toast',
    'vanillacookbook:fruit_salad',
    'vanillacookbook:garden_soup',
    'vanillacookbook:honey_cookie',
    'vanillacookbook:ice_cream',
    'vanillacookbook:mashed_potatoes',
    'vanillacookbook:meatloaf',
    'vanillacookbook:melon_juice',
    'vanillacookbook:milk_bottle',
    'vanillacookbook:pancake',
    'vanillacookbook:potato_chips',
    'vanillacookbook:pumpkin_soup',
    'vanillacookbook:trail_mix',

    // -- Pam HC2 FoodExt internal dupes (canonical: Pam HC2 Crops/FoodCore) --
    'pamhc2foodextended:bakedbeansitem',
    'pamhc2foodextended:carrotjuiceitem',
    'pamhc2foodextended:chocolatemilkitem',
    'pamhc2foodextended:chocolatemilkshakeitem',
    'pamhc2foodextended:crackersandcheeseitem',
    'pamhc2foodextended:friedonionsitem',
    'pamhc2foodextended:friedriceitem',
    'pamhc2foodextended:powdereddonutitem',

    // -- Cultural Delights raw-crop dupes (keep their prepared dishes) --
    'culturaldelights:avocado',
    'culturaldelights:avocado_sapling',
    'culturaldelights:cucumber',
    'culturaldelights:cucumber_seeds',
    'culturaldelights:cucumbers',
    'culturaldelights:eggplant',
    'culturaldelights:eggplant_seeds',
    'culturaldelights:eggplants',
    'culturaldelights:ginger',
    'culturaldelights:smoked_corn',
    'culturaldelights:smoked_eggplant',
    'culturaldelights:smoked_tomato',
    'culturaldelights:tortilla',

    // -- Delightful raw dupes (keep its prepared dishes) --
    'delightful:acorn',
    'delightful:cantaloupe',
    'delightful:cantaloupe_seeds',
  ]
  hides.forEach(id => {
    try { event.hide(id) } catch (e) { /* item may not exist if its mod is absent */ }
  })
  console.log(`[icraft food_dedup] Hid ${hides.length} duplicate food items from JEI`)
})
