
[types]

	[types.wood_type]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.blue_skies]
			crystallized = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			cherry = true

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.theabyss]
			blaru = true
			jungle = true
			slimed = true
			frozen = true
			vigilant = true

		[types.wood_type.thermal]
			rubberwood = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.extradelight]
			cinnamon = true

		[types.wood_type.valhelsia_structures]
			lapidified_jungle = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			cherry = true
			aurum = true
			edelwood = true

		[types.wood_type.cataclysm]
			chorus = true

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			fir = true
			redwood = true
			white_cherry = true
			pink_cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.blue_skies]
			crystallized = true
			crescent_fruit = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			cherry = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.thermal]
			rubberwood = true

		[types.leaves_type.occultism]
			otherworld = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.deep_aether]
			roseroot = true
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.simplefarming]
			apple = true
			apricot = true
			banana = true
			cherry = true
			mango = true
			olive = true
			orange = true
			pear = true
			plum = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.extradelight]
			cinnamon = true

		[types.leaves_type.forbidden_arcanus]
			cherry = true
			aurum = true
			nuggety_aurum = true

[entries]

	[entries.wood_type]

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			tiled_door = true
			pegged_planks = true
			secret_door = true
			smooth_planks = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			beach_door = true
			fine_vertical_planks = true
			diamond_bordered_glass = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			detailed_planks = true
			cobweb_trapdoor = true
			barred_trapdoor = true
			airy_trapdoor = true
			pressed_door = true
			planks_panel = true
			solid_trapdoor = true
			boarded_door = true
			meshed_trapdoor = true
			fancy_trapdoor = true
			paper_door = true
			basket_woven_planks = true
			enclosed_planks = true
			double_herringbone_planks = true
			crated_planks = true
			classic_windowed_trapdoor = true
			wickered_planks = true
			heavy_trapdoor = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			slotted_trapdoor = true
			polished_planks = true
			ornate_bared_glass_pane = true
			wall_torch = true
			glass_door = true
			paneled_door = true
			leafy_trapdoor = true
			pointless_trapdoor = true
			planks_shavings = true
			windowed_trapdoor = true
			tile_windowed_door = true
			golden_barred_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			classic_trapdoor = true
			circle_glass = true
			torch = true
			screen_door = true
			crossed_planks = true
			cross_laced_planks = true
			railed_planks = true
			planks_mosaic = true
			circle_glass_pane = true
			versailles_planks = true
			woven_glass = true
			woven_trapdoor = true
			gated_door = true
			supported_door = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			line_bared_glass = true
			slanted_planks = true
			barred_door = true
			suspicious_trapdoor = true
			herringbone_planks = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			tiled_planks = true
			dual_paneled_door = true
			square_glass_pane = true
			thin_planks = true
			warted_trapdoor = true
			horizontal_lined_glass = true
			natural_planks = true
			brick_bond_planks = true
			bordered_glass_pane = true
			sliding_door = true
			bordered_glass = true
			shack_door = true
			diagonal_planks = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			fortified_door = true
			snowflake_glass = true
			heavy_door = true
			stacked_planks = true
			twisted_trapdoor = true
			diamond_planks = true
			woven_glass_pane = true

		[entries.wood_type.mcwroofs]
			top_roof = true
			lower_roof = true
			planks_roof = true
			steep_roof = true
			planks_top_roof = true
			planks_upper_steep_roof = true
			upper_steep_roof = true
			upper_lower_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			roof = true
			planks_attic_roof = true
			planks_steep_roof = true
			planks_lower_roof = true

		[entries.wood_type.mcwfurnitures]
			stripped_glass_table = true
			end_table = true
			stool_chair = true
			stripped_drawer_counter = true
			stripped_counter = true
			covered_desk = true
			stripped_modern_wardrobe = true
			stripped_covered_desk = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			striped_chair = true
			stripped_large_drawer = true
			wardrobe = true
			modern_desk = true
			stripped_end_table = true
			drawer = true
			chair = true
			stripped_table = true
			double_drawer_counter = true
			drawer_counter = true
			counter = true
			table = true
			stripped_double_drawer = true
			lower_triple_drawer = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			stripped_desk = true
			stripped_lower_triple_drawer = true
			bookshelf_drawer = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_striped_chair = true
			stripped_stool_chair = true
			cupboard_counter = true
			coffee_table = true
			glass_table = true
			stripped_double_drawer_counter = true
			lower_bookshelf_drawer = true
			stripped_lower_bookshelf_drawer = true
			stripped_bookshelf_drawer = true
			stripped_bookshelf = true
			modern_chair = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			desk = true
			stripped_double_wardrobe = true
			triple_drawer = true
			double_wardrobe = true
			stripped_drawer = true

		[entries.wood_type.valhelsia_furniture]
			hay_chair = true
			desk = true
			chair = true
			table = true
			desk_drawer = true
			stool = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			log_bridge_stair = true
			rope_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.valhelsia_structures]
			post = true
			cut_stripped_post = true
			stripped_post = true
			cut_post = true

		[entries.wood_type.quark]
			vertical_planks = true
			hollow_log = true
			bookshelf = true
			ladder = true
			post = true
			trapped_chest = true
			chest = true
			stripped_post = true

		[entries.wood_type.mcwtrpdoors]
			swamp_trapdoor = true
			cottage_trapdoor = true
			classic_trapdoor = true
			bamboo_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			barred_trapdoor = true
			ranch_trapdoor = true
			beach_trapdoor = true
			glass_trapdoor = true
			blossom_trapdoor = true
			tropical_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			mystic_trapdoor = true
			barrel_trapdoor = true

		[entries.wood_type.twilightforest]
			hollow_log_climbable = true
			banister = true
			hollow_log_horizontal = true
			hollow_log_vertical = true

		[entries.wood_type.mcwfences]
			picket_fence = true
			wired_fence = true
			pyramid_gate = true
			highley_gate = true
			stockade_fence = true
			horse_fence = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.decorative_blocks]
			beam = true
			seat = true
			palisade = true
			support = true

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			full_drawers_4 = true
			full_drawers_1 = true
			half_drawers_1 = true
			half_drawers_4 = true
			half_drawers_2 = true
			trim = true

		[entries.wood_type.create]
			window_pane = true
			window = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.mcwfences]
			hedge = true

