
[General]
	#The speed of passive hunger.
	"Passive Hunger" = 25.0
	#The multiplier of the exhaustion that's added when having the hunger effect.
	"Hunger Effect Multiplier" = 5.0

[Regeneration]
	#The rate at which health is regenerated. Measured in health per seconds.
	"Health Regen Rate" = 12.0
	#The exhaustion added when using this mod's regen system.
	"Health Regen Exhaustion" = 3.0
	#The hunger threshold for when health is regenerated.
	"Health Regen Threshold" = 22.0

[Thresholds]
	#The threshold for when the WellFed effect is applied.
	"well Fed threshold" = 15.0
	#The threshold for when the hungry effect is applied.
	"Hungry Threshold" = 10.0
	#The threshold for when the starving effect is applied.
	"Starving Threshold" = 6.0

["No Saturation Hunger Drain Stuff"]
	#Sprint exhaustion
	"Sprint Exhaustion" = 4.0
	#Swim exhaustion
	"No Sat Swim Exhaustion" = 5.0
	#The multiplier for exhaustion increased when the player has no saturation left.
	"Other Actions" = 2.0

[Actions]
	#Additional swim exhaustion multiplier
	"Swim Exhaustion" = 2.25
	#The exhaustion added when breaking blocks.
	"Block Break Exhaustion" = 5.0
	#The exhaustion added when placing blocks.
	"Block Place Exhaustion" = 5.0
	#The exhaustion added when attacking an entity.
	"Attack exhaustion" = 2.0
	#Exhaustion added when tilling with a hoe.
	"Hoe Till" = 2.0
	#The multiplier of exhaustion points added when blocking with a shield.
	"Shield Block exhaustion" = 5.0

[Others]
	#The cooldown for the hunger sound. Measured in seconds.
	"Sound Cooldown" = 3.0
	#When value is 1, mining fatigue is applied to starving and hungry effect. if 2, only applies to starving effect. If 0, effect isn't applied.
	"Mining Fatigue Mode" = 1.0
	#The exhaustion added per each worn armor piece.
	"Armor Exhaustion Rate" = 4.0

[InnerMonologue]
	#The inner monologue for hunger.
	"Hunger Message" = "I'm hungry."
	#The inner monologue for starvation.
	"Starving Message" = "I'm starving!"

[Dizziness]
	#The chance for dizziness to occur.
	"Dizzy Chance" = 15.0
	#The hunger threshold for dizziness. If hunger is or below this value, dizziness can happen.
	"Dizzy Threshold" = 2.0
	#The length of dizziness. Measured in seconds.
	"Dizzy Length" = 15.0

[Faint]
	#The chance for a player to faint.
	"Faint Chance" = 10.0
	#The hunger threshold for player to faint. If hunger is or below this value, a player can faint.
	"Faint Threshold" = 2.0
	#The length of the faint effect. Measured in seconds.
	"Faint Length" = 15.0

["Tapeworm Mechanic"]
	#The chance to contract a tapeworm when eating raw food. Note: Not all modded foods are supported.
	"Tapeworm Chance" = 15.0
	#The rate at which exhaustion is increased during the Tapeworm Effect.
	"Tapeworm Rate" = 5.0
	#Length of Tapeworm Effect
	"Tapeworm Effect length" = 30.0

["Hunger Sleep"]
	#The exhaustion points added when waking up. 4 Full points equal to 1 hunger/saturation point drained.
	"Wake Up Exhaustion" = 0.0
	#The amount of hunger points decreased when waking up.
	"Wake Up Hunger" = 0.0

[Toggles]
	#Toggles the speed boost you get when sprinting while having the well-fed effect.
	"WellFed Swift" = false
	#Toggles the slowness effect you get when starving.
	"Hunger slowness" = true
	#Toggles whether or not you receive additional exhaustion point when wearing any armor pieces. May not be optimized.
	"Armor Exhaustion" = true
	#Toggles whether or not hunger sound is played.
	"Hunger Sound" = false
	#Toggless the tapeworm module.
	"Tapeworm Mechanics" = false
	#Toggles whether or not can you die of hunger.
	"Die of Hunger" = false
	#Toggle whether or not can you eat regardless how high your hunger is.
	Gluttony = false

["Advanced/Experimental"]
	#The cooldown for Gluttony. Measured in seconds.
	"Gluttony Cooldown" = 1.85
	#Toggles the hunger sleep module. Note: May not work, turn off at your own risk.
	"Hunger Sleep" = true
	#Toggle inner monologue.
	"Inner Monologue" = false

