#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Mar 17 17:49:41 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
