#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Mar 16 17:23:07 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
