#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Mar 18 18:29:36 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
