#Need help? Ask on Discord or Github/Gitlab <3 (ps: it is possible that this file contains nothing it's normal)
#Mon Jun 02 19:02:07 EDT 2025
int.villages.spacing=35
int.villages.separation=20
boolean.villages.enabled_custom_config=true
int.villages.salt=10387312
